### PR TITLE
#78: Improve flow issues

### LINKED ISSUE #78: Flow issues found during QA
- [x] Fix back button in `<Symptoms />` component to use the `history` back method
- [x] "Add my story" isn't working at all - you can't type.
- [x] The form contents in `<Questions />` should be loaded from the API
- [x] The link in `<Alert />` is broken

### PR DESCRIPTION
**Pull request by pyritewolf**
closes #78

### CODE REVIEW

File: frontend/src/routes/Symptoms/index.js [hunk 1]
```diff
@@ -124,7 +131,7 @@ export default function Symptoms(props) {
       <Fab
         style={{ background: "#9206FF" }}
         aria-label="Go to previous page"
-        onClick={navigate(paths.criticalQuestions)}
+        onClick={navigate()}
```
Comment (anaPerezGhiglia) [inline frontend/src/routes/Symptoms/index.js:134]: the removal of `paths.criticalQuestion` was intended?

Comment (pyritewolf) [reply frontend/src/routes/Symptoms/index.js:134]: Yep! We need to do the generic `history.goBack()` (as seen in `actions/story`) because you can reach the symptoms component from several different places, and when pressing this arrow, you should head back to wherever you were before.

File: frontend/src/routes/CriticalQuestions/index.js [hunk 2]
```diff
@@ -72,6 +72,18 @@ function CriticalQuestions(props) {
   const [contactCount, setContactCount] = useState(0);
   const [locationCount, setLocationCount] = useState(0);
 
+  let nextPage;
+  const { story } = useSelector((state) => state.story);
+  useEffect(() => {
+    if (!story) {
```
Comment (anaPerezGhiglia) [inline frontend/src/routes/CriticalQuestions/index.js:78]: what if there is no story because is the first time in the site? we should not go and fetch the story since there is nothing to fetch.
Is this being considered somewhere else in the codebase?

Comment (pyritewolf) [reply frontend/src/routes/CriticalQuestions/index.js:78]: This is covered by `fetchStory()` - essentially, we call the backend, it 404s, the `story` is set to `null` and that's it! This effect only runs when the `story` changes, so it's only fired once. The fields already have values because of the `formValues` default values, and those are never updated (because there's no story).
